# Generated by Django 4.1.5 on 2023-02-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city', 'state_name', 'state_id')},
        ),
    ]
