# Generated by Django 4.1.5 on 2023-03-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='geo_point',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='city',
            name='state_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='zip_code',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('zip_code', 'city_name', 'state_name')},
        ),
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
