# Generated by Django 4.1.5 on 2023-01-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_make', models.CharField(max_length=100)),
                ('pick_up_address', models.CharField(max_length=100)),
                ('drop_off_address', models.CharField(max_length=100)),
                ('pick_up_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
