# Generated by Django 4.1.5 on 2023-01-29 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='vehicle_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1931), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
