# Generated by Django 4.1.5 on 2023-03-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_models'),
        ('city', '0004_rename_city_city_city_name_and_more'),
        ('leads', '0002_alter_lead_vehicle_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='drop_off_address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='pick_up_address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='lead',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
            preserve_default=False,
        ),
    ]
