# Generated by Django 4.1.5 on 2023-03-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_models'),
        ('leads', '0003_remove_lead_drop_off_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='car_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
            preserve_default=False,
        ),
    ]
