# Generated by Django 4.1.5 on 2023-03-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_rename_city_city_city_name_and_more'),
        ('cars', '0006_alter_car_models'),
        ('leads', '0004_lead_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='car',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.AddField(
            model_name='lead',
            name='car_make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cars.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='drop_off_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_leads', to='city.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='pick_up_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_leads', to='city.city'),
            preserve_default=False,
        ),
    ]
