# Generated by Django 4.1.5 on 2023-03-29 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_car_remove_lead_city_lead_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='pick_up_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
