# Generated by Django 4.1.5 on 2023-03-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0006_alter_lead_pick_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='customers.customer'),
            preserve_default=False,
        ),
    ]
