# Generated by Django 4.1.5 on 2023-03-29 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='car_year',
            field=models.CharField(default=1, max_length=4, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
    ]
