# Generated by Django 4.1.5 on 2023-03-29 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0009_lead_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='clients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
