# Generated by Django 4.1.5 on 2023-03-29 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0010_alter_lead_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='car_year',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
