# Generated by Django 4.1.5 on 2023-02-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='models',
            field=models.ManyToManyField(blank=True, null=True, to='cars.carmodel'),
        ),
    ]
