# Generated by Django 4.1.5 on 2023-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='models',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='cars.carmodel'),
        ),
    ]
