# Generated by Django 4.1.5 on 2023-01-30 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_alter_lead_vehicle_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('key', models.CharField(default=keys.models.number_default_function, max_length=100, primary_key=True, serialize=False)),
                ('leads', models.ManyToManyField(blank=True, to='leads.lead')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
