# Generated by Django 4.1.5 on 2023-01-30 09:29

from django.db import migrations, models
import keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default=keys.models.number_default_function, max_length=100, unique=True),
        ),
    ]
